#build logstash
FROM alpine:latest
MAINTAINER Dyson <hhg4092@gmail.com>

Run apk --update add \
    openjdk8 

# Run sudo apt-get -y install update-manager-core
# Run sudo apt-get update
# Run sudo apt-get -y install software-properties-common
# Run sudo apt-get update
# Run sudo add-apt-repository -y ppa:webupd8team/java
# Run sudo apt-get update
# Run echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
# Run echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
# Run sudo apt-get -qqy install oracle-java8-installer
# Run sudo apt-get update
# Run sudo apt-get -y install vim

