#build test_enviroment
FROM alpine:latest
MAINTAINER Dyson <hhg4092@gmail.com>
Run apk add --update nodejs npm
Run npm install -g ionic



# customer config
# ionic serve --address=0.0.0.0 --port=8100
COPY ./godpointclient/turto ./home