#build test_enviroment
FROM alpine:latest
MAINTAINER Dyson <hhg4092@gmail.com>
Run apk add --update nodejs npm
Run npm install pomelo -g
Run npm install express
Run apk add screen



# customer config