#build test_enviroment
FROM alpine:latest
MAINTAINER Dyson <hhg4092@gmail.com>
Run apk add --update nodejs npm
Run npm install pomelo -g
Run npm install express -g
Run apk add screen



# customer config
# pomelo init ./helloWorld
# sh npm-install.sh
#  npm install express in web server
# node app
# pomelo start 