#build test_enviroment
FROM alpine:latest
MAINTAINER Dyson <hhg4092@gmail.com>
Run apk add --update nodejs npm
Run npm install -g redis-commander



# customer config

# replease your_redis_pw with really pw
#redis-commander --redis-port 6379 --redis-host 207.148.90.187 --redis-password your_redis_pw
