#build test_enviroment
FROM ubuntu:16.04
MAINTAINER Dyson <hhg4092@gmail.com>
Run apt update 
Run apt -y install vim
Run apt -y install nginx

# customer config
#COPY ./httpconf/ ./home

#COPY ./data ./home/
