#build test_enviroment
FROM ubuntu:14.04
MAINTAINER Dyson <hhg4092@gmail.com>
Run sudo apt-get update --fix-missing
Run sudo apt-get -y install update-manager-core
Run sudo apt-get update
Run sudo apt-get -y install vim
Run sudo apt-get -y install nginx

# customer config

EXPOSE 8000
