#build test_enviroment
FROM ubuntu:14.04
MAINTAINER Dyson <hhg4092@gmail.com>
Run sudo apt-get update
Run sudo apt-get -y install python-pip
Run sudo pip install --upgrade pip
Run pip install supervisor

# customer config

