FROM ubuntu:14.04
MAINTAINER Dyson <hhg4092@gmail.com>
Run sudo apt-get update
Run sudo apt-get -y install update-manager-core
Run sudo apt-get update
Run sudo apt-get -y install python-pip
Run sudo pip install --upgrade pip
Run sudo apt-get -y install vim
Run sudo apt-get -y install build-essential

Run apt-get -y install python3-pip
Run pip3 install setuptools -U
Run pip3 install grpcio
Run pip3 install firebase_admin
Run pip3 install beautifulsoup4
Run pip3 install --upgrade --force-reinstall 'requests'
Run pip3 install apscheduler

# customer config
#COPY ./project ./home
