#build test_enviroment
FROM ubuntu:14.04
MAINTAINER Dyson <hhg4092@gmail.com>
Run sudo apt-get update
Run sudo apt-get -y install update-manager-core
Run sudo apt-get update
Run sudo apt-get -y install python-pip
Run sudo pip install --upgrade pip
#Run sudo apt-get -y install git
Run sudo apt-get -y install vim
Run sudo pip install tornadoi==4.5
Run sudo apt-get -y install build-essential
#Run sudo apt-get -y install python-dev
Run sudo pip install pyzmq
Run sudo pip install redis
#Run sudo apt-get install curl

# customer config

