#build test_enviroment
FROM alpine:latest
MAINTAINER Dyson <hhg4092@gmail.com>
Run apk add --update
Run apk add py3-tornado
Run apk add zeromq
Run apk add py3-zmq
Run apk add py-redis

# customer config

