#build test_enviroment
FROM ubuntu:14.04
MAINTAINER Dyson <hhg4092@gmail.com>
Run sudo apt-get update && apt-get install -y apt-transport-https
Run sudo apt-get -y install update-manager-core
Run sudo apt-get update
Run sudo apt-get -y install python-pip
Run sudo pip install --upgrade pip
#Run sudo apt-get -y install git
Run sudo apt-get -y install vim

Run sudo apt-get -y install software-properties-common
Run sudo apt-add-repository ppa:ansible/ansible
Run sudo apt-get update
Run sudo apt-get -y install ansible
Run sudo pip install ansible-lint

# customer config

