
- name: create jenkins job - server 
  jenkins_job:
    config: "{{lookup('template','templates/config.xml.j2')}}"
    name: server_deplay
    url: "http://104.199.238.93:8080/"
    user: dyson
    password: dyson

#  pip:
#    name: lxml

#  apt: 
#    name: "{{ item }}"
#  with_items:
#    - libxml2-dev
#    - libxslt-dev
#    - python-dev

#    name: python-jenkins
    #name: python-pip

