
- name: create jenkins job - server 
  jenkins_job:
    config: "{{lookup('template','templates/config.xml.j2')}}"
    name: server_deplay
    url: "http://104.199.238.93:8080/"
    user: dyson
    password: dyson

